apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-cicd-demo
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - clerikc.ru
    secretName: clerikc-ru-tls
  rules:
  - host: clerikc.ru
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-cicd-demo
            port:
              number: 80